In [1]:
import numpy as np

In [3]:
def solve(a, b, c):
    x1 = (b**2) - (4*a*c)
    if x1 < 0:
        print("Solution will have imaginary roots.")
    else:
        print("Both roots will be real numbers.")
    x1 = x1**0.5
    x1 = (-b + x1) / 2*a
    x2 = (b**2) - (4*a*c)
    x2 = x1**0.5
    x1 = (-b - x1) / 2*a
    return x1, x2

def findRoot():
    A = float(input("Enter the value of a: "))
    B = float(input("Enter the value of b: "))
    C = float(input("Enter the value of c: "))
    print(solve(A, B, C))
    
findRoot()        

Enter the value of a:  2
Enter the value of b:  3
Enter the value of c:  4


Solution will have imaginary roots.
((-4.440892098500626e-16-4.795831523312719j), (1.1525741298268803+2.0804872325362127j))


In [7]:
def inputMatrix(name):
    box = []
    rows = input("Enter Number of rows: ")
    if rows == 'a':
        return None
    rows = int(rows)
    cols = input("Enter Number of columns: ")
    if rows == 'a':
        return None
    cols = int(cols)
    dim = rows * cols
    for i in range(rows):
        for j in range(cols):
            num = input("Enter {}{}{}:".format(name, i, j))
            if num == 'a':
                return None
            else:
                box.append(float(num))
    return np.array(box).reshape(rows, cols)

def multiplyMatrix():
    while True:
        print("Matrix A: ")
        A = inputMatrix('A')
        if A == None:
            break
        print("Matrix B: ")
        B = inputMatrix('B')
        if B == None:
            break
        try:
            result = np.matmul(A, B)
            print(result)
        except ValueError:
            print("Cannot Multiply this matrix.")
    print("Exit..")


multiplyMatrix()

Matrix A: 


Enter Number of rows:  a


Exit..


In [8]:
a_row_mat = np.array(np.pi)
a_row_mat

array(3.14159265)

In [9]:
b_row_mat = np.array(np.arange(-5, 5, 0.2))
b_row_mat

array([-5.0000000e+00, -4.8000000e+00, -4.6000000e+00, -4.4000000e+00,
       -4.2000000e+00, -4.0000000e+00, -3.8000000e+00, -3.6000000e+00,
       -3.4000000e+00, -3.2000000e+00, -3.0000000e+00, -2.8000000e+00,
       -2.6000000e+00, -2.4000000e+00, -2.2000000e+00, -2.0000000e+00,
       -1.8000000e+00, -1.6000000e+00, -1.4000000e+00, -1.2000000e+00,
       -1.0000000e+00, -8.0000000e-01, -6.0000000e-01, -4.0000000e-01,
       -2.0000000e-01,  4.4408921e-15,  2.0000000e-01,  4.0000000e-01,
        6.0000000e-01,  8.0000000e-01,  1.0000000e+00,  1.2000000e+00,
        1.4000000e+00,  1.6000000e+00,  1.8000000e+00,  2.0000000e+00,
        2.2000000e+00,  2.4000000e+00,  2.6000000e+00,  2.8000000e+00,
        3.0000000e+00,  3.2000000e+00,  3.4000000e+00,  3.6000000e+00,
        3.8000000e+00,  4.0000000e+00,  4.2000000e+00,  4.4000000e+00,
        4.6000000e+00,  4.8000000e+00])

In [10]:
A = np.array([[6, 0, 4], [1, 5, -3]])
B = np.array([[2, 9], [8, 0], [-4, 7]])

In [11]:
3*A

array([[18,  0, 12],
       [ 3, 15, -9]])

In [12]:
np.dot(A, B)

array([[ -4,  82],
       [ 54, -12]])

In [13]:
np.dot(B, A)

array([[ 21,  45, -19],
       [ 48,   0,  32],
       [-17,  35, -37]])