In [1]:
import numpy as np
from math import sqrt

In [1]:
def solve(a, b, c):
    x1 = (b**2) - (4*a*c)
    x1 = x1**0.5
    x1 = (-b + x1) / 2*a
    x2 = (b**2) - (4*a*c)
    x2 = x1**0.5
    x1 = (-b - x1) / 2*a
    print(type(x2))
    return x1, x2

In [2]:
solve(1, 4, 1)

<class 'complex'>


(-1.8660254037844386, (3.1696191514317656e-17+0.5176380902050416j))

In [ ]:
def mat_prod(A, B):
    TypeA = type(A)
    TypeB = type(B)
    if TypeA == '<class \'list\'>' and TypeB == '<class \'list\'>':
        arrA = np.array(A)
        arrB = np.array(B)
        return np.matmul(arrA, arrB)
    elif TypeA == '<class \'numpy.ndarray\'>' and TypeB == '<class \'numpy.ndarray\'>':
        return matmul(A, B)
        

In [45]:
import sympy

In [55]:
x1,x2,x3 = sympy.symbols('x1, x2, x3')

In [57]:
solution_eqn = sympy.solve([(x1-2*x2-x3-4), (3*x1 + 4*x2 + 2*x3 - 2), (5*x1 + 3*x2 - 5*x3 + 1)], dict = True)

In [58]:
solution_eqn

[{x1: 2, x2: -21/13, x3: 16/13}]

In [59]:
from sympy import cos, diff
x = sympy.Symbol('x')

In [60]:
y = cos(x)

In [63]:
dy_dx = diff(y, x)
dy_dx

-sin(x)

In [64]:
y = x**9 + 10*x**2 + 3*x

In [66]:
dy_dx = diff(y, x)
dy_dx

9*x**8 + 20*x + 3

In [70]:
from sympy import exp, sin
y = exp(sin(2*x))

In [71]:
dy_dx = diff(y, x)
dy_dx

2*exp(sin(2*x))*cos(2*x)

In [72]:
from sympy import integrate

In [80]:
y = cos(x)**4

In [81]:
solution = integrate(y, x)
solution

3*x/8 + sin(x)*cos(x)**3/4 + 3*sin(x)*cos(x)/8

In [82]:
exp = (3*x + 4*y)

In [84]:
solution = exp.subs({x:1, y:2})
solution

11

In [ ]:
def inputMatrix(name):
    box = []
    rows = int(input("Enter Number of rows: "))
    cols = int(input("Enter Number of columns: "))
    dim = rows * cols
    for i in range(rows):
        for j in range(cols):
            num = input("Enter {}{}{}:".format(name, i, j))
            if num == 'a':
                break
            else:
                box.append(float(num))
    return np.array(box).reshape(rows, cols)

def multiplyMatrix():
    while True:
        print("Matrix A: ")
        A = inputMatrix('A')
        print("Matrix B: ")
        B = inputMatrix('B')
        try:
            result = np.matmul(A, B)
            print(result)
        except ValueError:
            print("Cannot Multiply this matrix.")


multiplyMatrix()
    

Matrix A: 


Enter Number of rows:  2
Enter Number of columns:  2
Enter A00: 1
Enter A01: 2
Enter A10: 3
Enter A11: 4


Matrix B: 


Enter Number of rows:  2
Enter Number of columns:  2
Enter B00: 5
Enter B01: 6
Enter B10: 7
Enter B11: 8


[[19. 22.]
 [43. 50.]]
Matrix A: 


In [29]:
a_row_mat = np.array(np.pi)
a_row_mat

array(3.14159265)

In [33]:
b_row_mat = np.array(np.arange(-5, 5, 0.2))
b_row_mat

array([-5.0000000e+00, -4.8000000e+00, -4.6000000e+00, -4.4000000e+00,
       -4.2000000e+00, -4.0000000e+00, -3.8000000e+00, -3.6000000e+00,
       -3.4000000e+00, -3.2000000e+00, -3.0000000e+00, -2.8000000e+00,
       -2.6000000e+00, -2.4000000e+00, -2.2000000e+00, -2.0000000e+00,
       -1.8000000e+00, -1.6000000e+00, -1.4000000e+00, -1.2000000e+00,
       -1.0000000e+00, -8.0000000e-01, -6.0000000e-01, -4.0000000e-01,
       -2.0000000e-01,  4.4408921e-15,  2.0000000e-01,  4.0000000e-01,
        6.0000000e-01,  8.0000000e-01,  1.0000000e+00,  1.2000000e+00,
        1.4000000e+00,  1.6000000e+00,  1.8000000e+00,  2.0000000e+00,
        2.2000000e+00,  2.4000000e+00,  2.6000000e+00,  2.8000000e+00,
        3.0000000e+00,  3.2000000e+00,  3.4000000e+00,  3.6000000e+00,
        3.8000000e+00,  4.0000000e+00,  4.2000000e+00,  4.4000000e+00,
        4.6000000e+00,  4.8000000e+00])

In [34]:
A = np.array([[6, 0, 4], [1, 5, -3]])
B = np.array([[2, 9], [8, 0], [-4, 7]])

In [35]:
3*A

array([[18,  0, 12],
       [ 3, 15, -9]])

In [36]:
np.dot(A, B)

array([[ -4,  82],
       [ 54, -12]])

In [37]:
np.dot(B, A)

array([[ 21,  45, -19],
       [ 48,   0,  32],
       [-17,  35, -37]])